-- CREATE DATABASE Assignment5;
USE Assignment5;
-- Create the tables
CREATE TABLE CUSTOMER(
CUST_NUM INT,
CUST_LNAME VARCHAR(255),
CUST_FNAME VARCHAR(255),
CUST_BALANCE FLOAT);

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (CUST_NUM);

CREATE TABLE CUSTOMER_2(
CUST_NUM INT,
CUST_LNAME VARCHAR(255),
CUST_FNAME VARCHAR(255));

CREATE TABLE INVOICE(
INV_NUM INT,
CUST_NUM INT,
INV_DATE DATE,
INV_AMOUNT FLOAT);

ALTER TABLE INVOICE
ADD foreign key(CUST_NUM) references CUSTOMER(CUST_NUM);

INSERT INTO CUSTOMER(CUST_NUM, CUST_LNAME, CUST_FNAME, CUST_BALANCE)
VALUES
(1000, 'Smith', 'Jeanne', 1050.11),
(1001, 'Ortega', 'Juan', 840.92);

INSERT INTO CUSTOMER_2(CUST_NUM, CUST_LNAME, CUST_FNAME)
VALUES
(2000, 'McPherson', 'Anne'),
(2001, 'Ortega', 'Juan'),
(2002, 'Kowalski', 'Jan'),
(2003, 'Chen', 'George');

INSERT INTO INVOICE(INV_NUM, CUST_NUM, INV_DATE, INV_AMOUNT)
VALUES
(8000, 1000, '2016-03-23', 235.89),
(8001, 1001, '2016-03-23', 312.82),
(8002, 1001, '2016-03-30', 528.10),
(8003, 1000, '2016-04-12', 194.78),
(8004, 1000, '2016-04-16', 619.44);

SELECT CUSTOMER.CUST_LNAME, CUSTOMER.CUST_FNAME FROM CUSTOMER
UNION ALL
SELECT CUSTOMER_2.CUST_LNAME, CUSTOMER_2.CUST_FNAME FROM CUSTOMER_2;

SELECT CUSTOMER.CUST_LNAME, CUSTOMER.CUST_FNAME FROM CUSTOMER
UNION 
SELECT CUSTOMER_2.CUST_LNAME, CUSTOMER_2.CUST_FNAME FROM CUSTOMER_2;

SELECT CUST_LNAME, CUST_FNAME
FROM( 
SELECT CUST_LNAME, CUST_FNAME FROM CUSTOMER
UNION ALL
SELECT CUST_LNAME, CUST_FNAME FROM CUSTOMER_2) AS theTable
GROUP BY CUST_LNAME, CUST_FNAME HAVING COUNT(*) > 1;

SELECT CUST_LNAME, CUST_FNAME FROM CUSTOMER_2
WHERE(CUST_LNAME, CUST_FNAME) 
NOT IN (SELECT CUST_LNAME, CUST_FNAME FROM CUSTOMER);

SELECT INVOICE.INV_NUM, INVOICE.CUST_NUM, CUSTOMER.CUST_FNAME, CUSTOMER.CUST_LNAME, INVOICE.INV_DATE, INVOICE.INV_AMOUNT
FROM INVOICE
INNER JOIN CUSTOMER ON INVOICE.CUST_NUM = CUSTOMER.CUST_NUM
WHERE CUSTOMER.CUST_BALANCE >= 1000;

SELECT INV_NUM, INV_AMOUNT, (SELECT AVG(INV_AMOUNT) FROM INVOICE), (SELECT AVG(INV_AMOUNT) FROM INVOICE) - INV_AMOUNT FROM INVOICE;


CREATE TABLE new_INVOICE(
INV_NUM INT auto_increment primary key,
CUST_NUM INT ,
INV_DATE DATE,
INV_AMOUNT FLOAT,
foreign key(CUST_NUM) references CUSTOMER(CUST_NUM))
auto_increment = 5000;

INSERT INTO new_INVOICE( CUST_NUM, INV_DATE, INV_AMOUNT)
VALUES
(1000, '2016-03-23', 235.89),
(1001, '2016-03-23', 312.82),
(1001, '2016-03-30', 528.10),
(1000, '2016-04-12', 194.78),
(1000, '2016-04-16', 619.44);

SELECT * FROM new_INVOICE;



ALTER TABLE CUSTOMER ADD CUST_DOB DATE;
ALTER TABLE CUSTOMER ADD CUST_AGE DOUBLE;

UPDATE CUSTOMER set CUST_DOB ='1979-03-15' WHERE CUST_NUM = 1000;
UPDATE CUSTOMER set CUST_DOB ='1988-12-22' WHERE CUST_NUM = 1001;

UPDATE CUSTOMER set CUST_AGE = TIMESTAMPDIFF(YEAR,'1979-03-15',CURDATE()) WHERE CUST_NUM = 1000;
UPDATE CUSTOMER set CUST_AGE = TIMESTAMPDIFF(YEAR,'1988-12-22',CURDATE()) WHERE CUST_NUM = 1001;

-----------------------------------------------------------------------------------------------------
-- CREATE DATABASE assignment5_question2;

USE assignment5_question2;


CREATE TABLE DEPARTMENT(
Dname varchar(255),
Dnumber int,
Mgr_ssn bigint,
Mgr_start_date date,
primary key(Dnumber));



CREATE TABLE DEPT_LOCATIONS(
Dnumber int, 
Dlocation varchar(255),
primary key(Dnumber, Dlocation),
foreign key(Dnumber) references DEPARTMENT(Dnumber));



CREATE TABLE PROJECT(
Pname varchar(255),
Pnumber int,
Plocation varchar(255),
Dnum int,
primary key(Pnumber),
foreign key(Dnum) references DEPARTMENT(Dnumber));



CREATE TABLE EMPLOYEE(
Fname varchar(255),
Minit char(1),
Lname varchar(255),
Ssn BIGINT,
Bdate Date,
Address varchar(255),
Sex char(1),
Salary int,
Super_ssn bigint,
Dno int,
primary key(Ssn),
foreign key(Dno) references DEPARTMENT(Dnumber));



CREATE TABLE WORKS_ON(
Essn bigint,
Pno int,
Hours double,
primary key(Essn, Pno),
foreign key(Pno) references PROJECT(Pnumber),
foreign key(Essn) references EMPLOYEE(Ssn));


CREATE TABLE DEPENDENT(
Essn bigint,
Dependent_name varchar(255),
Sex char(1),
Bdate date,
Relationship varchar(255),
primary key(Essn, Dependent_name),
foreign key(Essn) references EMPLOYEE(Ssn));


INSERT INTO EMPLOYEE(Fname, Minit, Lname, Ssn, Bdate, Address, Sex, Salary, Super_ssn, Dno)
VALUES
('John', 'B', 'Smith', 123456789, '1965-01-09', '731 Fondren', 'M', 30000, 333445555,5),
('Franklin', 'T', 'Wong', 333445555, '1955-12-08', '638 Voss', 'M', 40000, 888665555, 5);

INSERT INTO EMPLOYEE(Fname, Minit, Lname, Ssn, Bdate, Address, Sex, Salary, Super_ssn, Dno)
VALUES
('James', 'E', 'Borg', 888665555, '1937-11-10', '450 Stone', 'M', 55000, NULL, 1);

INSERT INTO DEPARTMENT(Dname, Dnumber, Mgr_ssn, Mgr_start_date)
VALUES
('Research', 5, 333445555, '1988-05-22'),
('Administration', 4, 987654321, '1995-01-01');

INSERT INTO DEPARTMENT(Dname, Dnumber, Mgr_ssn, Mgr_start_date)
VALUES
('Headquarters', 1, 888665555, '1981-06-19' );

INSERT INTO DEPT_LOCATIONS(Dnumber, Dlocation)
VALUES
(4, 'Stafford'),
(5, 'Bellaire'),
(5, 'Sugarland'),
(5, 'Houston');

INSERT INTO DEPT_LOCATIONS(Dnumber, Dlocation)
VALUES
(1, 'Houston');

INSERT INTO PROJECT(Pname, Pnumber, Plocation, Dnum)
VALUES
('ProductX', 1, 'Bellaire', 5),
('ProductY', 2, 'Sugarland', 5),
('ProductZ', 3, 'Houston', 5),
('Computerization', 10, 'Stafford', 4),
('Reorganization', 20, 'Houston', 1),
('Newbenefits', 30, 'Stafford', 4);

INSERT INTO WORKS_ON(Essn, Pno, Hours)
VALUES
(123456789, 1, 32.5),
(123456789, 2, 7.5);

INSERT INTO DEPENDENT(Essn, Dependent_name, Sex, Bdate, Relationship)
VALUES
(123456789, 'Michael', 'M', '1988-01-01', 'Son');

INSERT INTO DEPENDENT(Essn, Dependent_name, Sex, Bdate, Relationship)
VALUES
(123456789, 'Alice', 'F', '1988-12-30', 'Daughter'),
(123456789, 'Elizabeth', 'F', '1987-05-05', 'Spouse');



SELECT EMPLOYEE.Fname, EMPLOYEE.Lname
FROM PROJECT
INNER JOIN WORKS_ON ON PROJECT.Pnumber = WORKS_ON.Pno
INNER JOIN EMPLOYEE ON WORKS_ON.Essn = EMPLOYEE.Ssn
WHERE EMPLOYEE.Dno = 5 AND WORKS_ON.Hours > 10 AND PROJECT.Pname = 'ProductX';


SELECT EMPLOYEE.Fname, EMPLOYEE.Lname
FROM EMPLOYEE
INNER JOIN DEPENDENT ON EMPLOYEE.Ssn = DEPENDENT.Essn
WHERE EMPLOYEE.Fname = DEPENDENT.Dependent_name;


SELECT Fname, Lname FROM EMPLOYEE WHERE Super_ssn = (SELECT Ssn FROM EMPLOYEE WHERE Fname = 'Franklin' and Lname = 'Wong');

SELECT Fname, Lname FROM EMPLOYEE WHERE Lname LIKE 'W%';

SELECT Fname, Lname FROM EMPLOYEE WHERE Salary > 40000;

SELECT EMPLOYEE.Fname, EMPLOYEE.Lname
FROM EMPLOYEE
INNER JOIN DEPARTMENT ON EMPLOYEE.Dno = DEPARTMENT.Dnumber
WHERE Dname = 'Research';



SELECT DEPARTMENT.Dname, COUNT(*)
FROM DEPARTMENT 
INNER JOIN EMPLOYEE ON DEPARTMENT.Dnumber = EMPLOYEE.Dno
GROUP BY DEPARTMENT.Dnumber HAVING COUNT(*) < 4;


SELECT Fname, Lname FROM EMPLOYEE WHERE Super_ssn is NULL;

SELECT DEPARTMENT.Dnumber, COUNT(DEPARTMENT.Dnumber)
FROM DEPARTMENT 
INNER JOIN EMPLOYEE ON DEPARTMENT.Dnumber = EMPLOYEE.Dno
GROUP BY DEPARTMENT.Dnumber;

-------------------------------------------------------------------------------

-- CREATE DATABASE assignment5_question3;

USE assignment5_question3;

CREATE TABLE Customer(
CUST_FNAME VARCHAR(255),
CUST_LNAME VARCHAR(255),
CUST_STREET VARCHAR(255),
CUST_CITY VARCHAR(255),
CUST_STATE VARCHAR(255),
CUST_ZIP INT);

INSERT INTO Customer(CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP)
VALUES
('LUPE', 'SANTANA', '1292 WEST', 'Phenix city', 'AL', 36867);

INSERT INTO Customer(CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP)
VALUES
('MELONIE', 'JIMENEZ', '848 DOWNEY', 'EAST MONKTON', 'VT', 05443);

CREATE TABLE Employee(
EMP_NUM INT,
EMP_LNAME VARCHAR(255),
EMP_EMAIL VARCHAR(255),
EMP_TITLE VARCHAR(255),
DEPT_NAME VARCHAR(255),
primary key(EMP_NUM));


INSERT INTO Employee(EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE, DEPT_NAME)
VALUES
(84526, 'LASSITER', 'F.LASSIT8@LGCOMPANY.COM', 'ASSOCIATE', 'ACCOUNTING');




CREATE TABLE Brand(
BRAND_ID INT,
BRAND_NAME VARCHAR(255),
AVGPRICE DOUBLE,
primary key(BRAND_ID, BRAND_NAME),
unique key(BRAND_NAME));

INSERT INTO Brand(BRAND_ID, BRAND_NAME, AVGPRICE)
VALUES
(33, 'BINDER PRIME', 16.12),
(29, 'BUSTERS', 22.59);


CREATE TABLE Brand_name_num(
BRAND_NAME VARCHAR(255),
NUMPRODUCTS_BRAND INT,
primary key(BRAND_NAME),
foreign key(BRAND_NAME) references Brand(BRAND_NAME));

INSERT INTO Brand_name_num(BRAND_NAME, NUMPRODUCTS_BRAND)
VALUES
('BINDER PRIME', 27);


CREATE TABLE Brand_id_inv(
BRAND_ID INT,
TOTALINVENTORY INT,
primary key(BRAND_ID),
foreign key(BRAND_ID) references Brand(BRAND_ID));

INSERT INTO Brand_id_inv(BRAND_ID, TOTALINVENTORY)
VALUES
(33, 2158),
(29, 1735);


CREATE TABLE Dept_recent(
DEPT_NUM INT,
MOSTRECENT Date);

INSERT INTO Dept_recent(DEPT_NUM, MOSTRECENT)
VALUES
(200, '2005-06-08'),
(250, '2015-12-15');

CREATE TABLE Prod_num(
PROD_CATEGORY VARCHAR(255),
NUMPRODUCTS_PROD INT);

INSERT INTO Prod_num(PROD_CATEGORY, NUMPRODUCTS_PROD)
VALUES
('Cleaner', 2),
('Filler', 2);

CREATE TABLE Prod_detailed_num(
PROD_BASE VARCHAR(255),
PROD_TYPE VARCHAR(255),
NUMPRODUCTS_Prod_detailed_num INT);

INSERT INTO Prod_detailed_num(PROD_BASE, PROD_TYPE, NUMPRODUCTS_Prod_detailed_num)
VALUES
('Solvent', 'Exterior', 67);

INSERT INTO Prod_detailed_num(PROD_BASE, PROD_TYPE, NUMPRODUCTS_Prod_detailed_num)
VALUES
('Water', 'Exterior', 39),
('Water', 'Interior', 63);

INSERT INTO Prod_detailed_num(PROD_BASE, PROD_TYPE, NUMPRODUCTS_Prod_detailed_num)
VALUES
('Solvent', 'Interior', 83);




SELECT CUST_FNAME, CUST_LNAME FROM Customer WHERE CUST_STATE = 'NY';

SELECT COUNT(CUST_FNAME), CUST_STATE FROM Customer GROUP BY CUST_STATE ORDER BY COUNT(CUST_FNAME) DESC;

SELECT Brand.BRAND_NAME, Brand_name_num.NUMPRODUCTS_BRAND AS Number_of_Products
FROM Brand
INNER JOIN Brand_name_num ON Brand.BRAND_NAME = Brand_name_num.BRAND_NAME
ORDER BY Brand.BRAND_NAME;

SELECT EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE, DEPT_NAME FROM Employee 
WHERE EMP_TITLE LIKE '%ASSOCIATE' ORDER BY DEPT_NAME, EMP_TITLE;

SELECT NUMPRODUCTS_Prod_detailed_num, PROD_TYPE, PROD_BASE FROM Prod_detailed_num WHERE PROD_BASE = 'Water';

SELECT PROD_BASE,PROD_TYPE, SUM(NUMPRODUCTS_Prod_detailed_num)FROM Prod_detailed_num 
GROUP BY PROD_TYPE, PROD_BASE;

SELECT BRAND_ID, SUM(TOTALINVENTORY) FROM Brand_id_inv GROUP BY BRAND_ID ORDER BY BRAND_ID DESC;

SELECT CUST_FNAME, CUST_LNAME FROM Customer WHERE CUST_STATE = 'FL';

SELECT BRAND_ID, BRAND_NAME, AVGPRICE FROM Brand ORDER BY BRAND_NAME;

SELECT DEPT_NUM , MOSTRECENT FROM Dept_recent ORDER BY DEPT_NUM;





